routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Route::get('/contact', function () {
    return view('contact');
});

Route::post('/send-email', function () {
    return "/send-email";
})->name('contact');

Route::get('/page/about', 'PageController@show');

Route::resource('/posts', 'PostController');

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Class City
 * @package App
 * @mixin Builder
 */
class City extends Model
{
    protected $table = 'city';

}

app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Country
 * @package App
 * @mixin Builder;
 */
class Country extends Model
{
    protected $table = 'country';
    protected $primaryKey = 'Code';
    public $incrementing = false;
    protected $keyType = 'string';

}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Post
 * @package App
 * @mixin Builder
 */
class Post extends Model
{
    //protected $table = 'posts';
    //protected $primaryKey = 'post_id';
    //public $incrementing = false;
    //protected $keyType = 'string';
    //public $timestamps = false;
//    protected $attributes = [
//      'content' => 'Lorem ipsum...',
//    ];

    protected $fillable = ['title', 'content'];

    public function rubric(){
        return $this->belongsTo(Rubric::class);
    }

    public function tags(){
        return $this->belongsToMany(Tag::class);
    }
}

app/Rubric.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rubric extends Model
{
    public function post(){
//        $this->hasOne('App\Post');
        $this->hasOne(Post::class);
    }
    public function posts(){
        return $this->hasMany('App\Post');
    }
}

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts(){
        return $this->belongsToMany(Post::class);
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use App\Country;
use App\Post;
use App\Rubric;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PageController extends Controller
{
    public function index()
    {
//        $query = DB::insert("INSERT INTO posts (title, content) VALUES (?, ?)", ['Статья 3', 'Lorem ipsum 3']);
//        var_dump($query);
//        $posts = DB::select("SELECT * FROM posts");

//        $data = DB::table('country')->get();
//        $data = DB::table('city')->select('ID', 'Name')->find(2);
//        dd($data);
//        $post = new Post();
//        $post->title = 'Content 1';
//        $post->content = 'Lorem ipsum 1';
//        $post->save();
//        $data = Country::where('Code', '<', 'ALB')->get();
//        $data = Country::find('AGO');
//        Post::create(['title' => 'Post 5', 'content' => 'Lorem ipsum 123']);
//        $post = Post::find(6);
//        $post->content = 'Lorem ipsum 6';
//        $post->save();

//        $post = Post::find(5);
//        dump($post->title, $post->rubric->title);
//        $rubric = Rubric::find(2);
//        dump($rubric->posts);
//        $posts = Post::where('id', '>', 1)->get();
//        foreach ($posts as $post)
//        {
//            dump($post->title);
//        }
//        $post = Post::find(3);
//        dump($post->title);
//        foreach ($post->tags as $tag)
//        {
//            dump($tag->title);
//        }
        $tag = Tag::find(1);
        dump($tag->title);
        foreach ($tag->posts as $post)
        {
            dump($post->title);
        }
//        return $post;
    }

    public function show()
    {
        return view('pages.about');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostController extends Controller
{

    public function __construct(Request $request)
    {
        dump($request->route()->getName());
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        $posts = DB::select("SELECT * FROM posts");
//        return $posts;
        return view('posts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request->title);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return "Post $id";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('posts.edit', ['id' => $id]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        dump($id);
        dd($request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dump(__METHOD__);
        dd($id);
    }
}

resources/views/contact.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="{{route('contact')}}" method="post">
{{--    {{csrf_field()}}--}}
    @csrf
    <input type="text" name="name">
    <input type="email" name="email">
    <button type="submit">Submit</button>
</form>
</body>
</html>

resources/views/pages/about.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>About Page</h1>
</body>
</html>

resources/views/posts/create.blade.php
<!doctype html>
<html lang="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="{{route('posts.store')}}" method="post">
    @csrf
    <input type="text" name="title">
    <button type="submit">Submit</button>
</form>
</body>
</html>

resources/views/posts/edit.blade.php
<!doctype html>
<html lang="">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form action="{{route('posts.update', ['post' => $id])}}" method="post">
    @csrf
    @method('PUT')
    <input type="text" name="title">
    <button type="submit">Submit</button>
</form>
</body>
</html>

resources/views/posts/index.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1></h1>
<ul>
    <li>
        <a href="{{route('posts.show', ['post' => 1])}}">Post 1</a>
        <a href="{{route('posts.edit', ['post' => 1])}}">Edit</a>
        <form action="{{route('posts.destroy', ['post' => 1])}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Delete</button>
        </form>
    </li>
    <li>
        <a href="{{route('posts.show', ['post' => 2])}}">Post 2</a>
        <a href="{{route('posts.edit', ['post' => 2])}}">Edit</a>
        <form action="{{route('posts.destroy', ['post' => 2])}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Delete</button>
        </form>
    </li>
    <li>
        <a href="{{route('posts.show', ['post' => 3])}}">Post 3</a>
        <a href="{{route('posts.edit', ['post' => 3])}}">Edit</a>
        <form action="{{route('posts.destroy', ['post' => 3])}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Delete</button>
        </form>
    </li>
</ul>
</body>
</html>